### ISSUE TITLE
[oss] 腾讯COS在此项目下不能正常工作, 需要做什么特殊配置吗

### ISSUE THREAD

**Issue by Alice52** [hujiaqing789/test-spring-boot-starter#1]

**Comment by hujiaqing789** [comment]
您好，您是解决了嘛？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月24日(星期五) 下午3:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [hujiaqing789/test-spring-boot-starter] [oss] 腾讯COS在此项目下不能正常工作, 需要做什么特殊配置吗 (Issue #1)





 
Closed #1 as completed.

**Comment by Alice52** [comment]
是因为 腾讯COS 的bucket name 有格式要求 <bucketname>-<appid> 导致的额

**Comment by hujiaqing789** [comment]
好的，你可以看具体的报错信息，这种问题应该很好解决，俺因为没有腾讯的cos没法跟您演示。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月27日(星期一) 上午8:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hujiaqing789/test-spring-boot-starter] [oss] 腾讯COS在此项目下不能正常工作, 需要做什么特殊配置吗 (Issue #1)





 
是因为 腾讯COS 的bucket name 有格式要求 - 导致的额
